name = "browser-worker"
main = "src/index.ts"
compatibility_date = "2023-03-14"
compatibility_flags = [ "nodejs_compat" ]

browser = { binding = "MYBROWSER" }
kv_namespaces = [
  { binding = "SCREENSHOT_KV", id = "a10d290cf68843efacfca7141a1d6aa3", preview_id = "e9c442e2f0064bcc964d0f2d9d3612d8" }
]